### ISSUE TITLE
Error on bench build

### ISSUE THREAD

**Issue by dhsathiya** [rtCamp/next-crm#46]
```
╰─➤  bench build --app next_crm                                                                                                                                                            1 ↵
✔ Application Assets Linked


yarn run v1.22.22
$ node esbuild --apps next_crm --run-build-command
File                                                        Size

 DONE  Total Build Time: 191.923ms


Running build command for next_crm
$ cd frontend && yarn build
$ vite build --base=/assets/next_crm/frontend/ && yarn copy-html-entry
failed to load config from /workspace/frappe-bench/apps/next_crm/frontend/vite.config.js
error during build:
Error [ERR_REQUIRE_ESM]: require() of ES Module /workspace/frappe-bench/apps/next_crm/node_modules/strip-ansi/index.js from /workspace/frappe-bench/apps/next_crm/node_modules/ora/index.js not supported.
Instead change the require of /workspace/frappe-bench/apps/next_crm/node_modules/strip-ansi/index.js in /workspace/frappe-bench/apps/next_crm/node_modules/ora/index.js to a dynamic import() which is available in all CommonJS modules.
    at _require.extensions.<computed> [as .js] (file:///workspace/frappe-bench/apps/next_crm/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:66358:17)
    at Object.<anonymous> (/workspace/frappe-bench/apps/next_crm/node_modules/ora/index.js:7:19)
    at _require.extensions.<computed> [as .js] (file:///workspace/frappe-bench/apps/next_crm/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:66358:17)
    at Object.<anonymous> (/workspace/frappe-bench/apps/next_crm/node_modules/frappe-ui/scripts/generateInterface.js:3:13)
    at _require.extensions.<computed> [as .js] (file:///workspace/frappe-bench/apps/next_crm/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:66358:17)
    at Object.<anonymous> (/workspace/frappe-bench/apps/next_crm/node_modules/frappe-ui/vite.js:3:35)
    at _require.extensions.<computed> [as .js] (file:///workspace/frappe-bench/apps/next_crm/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:66358:17)
    at Object.<anonymous> (/workspace/frappe-bench/apps/next_crm/frontend/vite.config.js:39:28)
    at _require.extensions.<computed> [as .js] (file:///workspace/frappe-bench/apps/next_crm/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:66355:24)
    at loadConfigFromBundledFile (file:///workspace/frappe-bench/apps/next_crm/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:66363:21)
    at async loadConfigFromFile (file:///workspace/frappe-bench/apps/next_crm/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:66186:28)
    at async resolveConfig (file:///workspace/frappe-bench/apps/next_crm/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:65782:28)
    at async build (file:///workspace/frappe-bench/apps/next_crm/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:47926:20)
    at async CAC.<anonymous> (file:///workspace/frappe-bench/apps/next_crm/node_modules/vite/dist/node/cli.js:842:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed: yarn build
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at run_build_command_for_apps (/workspace/frappe-bench/apps/frappe/esbuild/esbuild.js:448:5)
    at execute (/workspace/frappe-bench/apps/frappe/esbuild/esbuild.js:125:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 51824,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by dhsathiya** [comment]
The issue was from upstream. It has been fixed by @Aryan20
